spring.application.name=test-suspend
rest-client.thread-count=16
rest-client.timeout-millis=10000
rest-client.max-connections-count=64
rest-client.max-connections-per-route=16
rest-client.keep-alive-time-millis=5000
rest-client.connect-attempts=1
rest-client.request-id-header-name=X-Request-Id
rest-client.create-payment-url=https://example.org/payments
rest-client.resolve-customer-url=https://example.org/customers/resolve
