spring.application.name=test-suspend
rest-client.timeout-millis=10000
rest-client.max-connections-count=64
rest-client.max-connections-per-route=16
rest-client.keep-alive-time-millis=5000
rest-client.connect-attempts=1
rest-client.base-url=https://example.org
rest-client.create-payment-path=/payments
rest-client.resolve-customer-path=/customers/resolve
